Ensure correct number of args are used
```bash
 $ go run main.go operator deploy versions
Error: accepts 0 arg(s), received 1
Usage:
  jsctl operator deploy [flags]
...

```

Signed-off-by: Charlie Egan <charlieegan3@users.noreply.github.com>